Repository dbt-labs/dbt-postgres, pull requests merged in 2024-07, with the labels that each got.

#98 Support persisting docs for `materialized_view` materializations
  .changes/unreleased/Fixes-20240626-163930.yaml
  dbt/include/postgres/macros/adapters.sql
  tests/functional/shared_tests/test_persist_docs.py
Labels: cla:yes, ok to test

#119 Base 207/add test
  tests/functional/shared_tests/test_show.py
Labels: cla:yes, Skip Changelog

#127 Remove snapshot tests
  tests/functional/adapter/__init__.py
  tests/functional/adapter/test_aliases.py
  tests/functional/adapter/test_basic.py
  tests/functional/adapter/test_caching.py
  tests/functional/adapter/test_clone.py
  tests/functional/adapter/test_column_types.py
  tests/functional/adapter/test_concurrency.py
  tests/functional/adapter/test_constraints.py
  tests/functional/adapter/test_data_types.py
  tests/functional/adapter/test_debug.py
  tests/functional/adapter/test_empty.py
  tests/functional/adapter/test_ephemeral.py
  tests/functional/adapter/test_grants.py
  tests/functional/adapter/test_hooks/data/seed_model.sql
  tests/functional/adapter/test_hooks/data/seed_run.sql
  tests/functional/adapter/test_hooks/test_hooks.py
  tests/functional/adapter/test_incremental.py
  tests/functional/adapter/test_persist_docs.py
  tests/functional/adapter/test_query_comment.py
  tests/functional/adapter/test_relations.py
  tests/functional/adapter/test_show.py
  tests/functional/adapter/test_simple_copy.py
  tests/functional/adapter/test_simple_seed/seed_bom.csv
  tests/functional/adapter/test_simple_seed/test_simple_seed.py
  tests/functional/adapter/test_simple_snapshot.py
  tests/functional/adapter/test_store_test_failures.py
  tests/functional/adapter/test_unit_testing.py
  tests/functional/adapter/test_utils.py
  tests/functional/simple_snapshot/data/invalidate_postgres.sql
  tests/functional/simple_snapshot/data/seed_pg.sql
  tests/functional/simple_snapshot/data/shared_macros.sql
  tests/functional/simple_snapshot/data/update.sql
  tests/functional/simple_snapshot/fixtures.py
  tests/functional/simple_snapshot/test_basic_snapshot.py
  tests/functional/simple_snapshot/test_changing_check_cols_snapshot.py
  tests/functional/simple_snapshot/test_changing_strategy_snapshot.py
  tests/functional/simple_snapshot/test_check_cols_snapshot.py
  tests/functional/simple_snapshot/test_check_cols_updated_at_snapshot.py
  tests/functional/simple_snapshot/test_comment_ending_snapshot.py
  tests/functional/simple_snapshot/test_cross_schema_snapshot.py
  tests/functional/simple_snapshot/test_hard_delete_snapshot.py
  tests/functional/simple_snapshot/test_invalid_namespace_snapshot.py
  tests/functional/simple_snapshot/test_long_text_snapshot.py
  tests/functional/simple_snapshot/test_renamed_source_snapshot.py
  tests/functional/simple_snapshot/test_select_exclude_snapshot.py
  tests/functional/simple_snapshot/test_slow_query_snapshot.py
Labels: cla:yes, Skip Changelog

#123 Add record/replay support
  .changes/unreleased/Under the Hood-20240716-172442.yaml
  dbt/adapters/postgres/connections.py
  dbt/adapters/postgres/record/__init__.py
  dbt/adapters/postgres/record/cursor/cursor.py
  dbt/adapters/postgres/record/cursor/status.py
  dbt/adapters/postgres/record/handle.py
Labels: cla:yes

#126 Simplify hatch setup
  .github/workflows/integration-tests.yml
  .github/workflows/release_prep_hatch.yml
  .github/workflows/unit-tests.yml
  CONTRIBUTING.md
  pyproject.toml
Labels: cla:yes, Skip Changelog

#95 Bump deps on common, adapters, core
  pyproject.toml
Labels: cla:yes, Skip Changelog

#131 Add hatch commands to the README
  README.md
Labels: cla:yes, Skip Changelog

#128 Make `dependabot` ignore patch updates
  .github/dependabot.yml
Labels: cla:yes, Skip Changelog
