Repository dbt-labs/dbt-postgres, pull requests merged in 2024-06, with the labels that each got.

#114 delete more Core only Tests
  tests/functional/artifacts/data/results/v4/run_results.json
  tests/functional/artifacts/data/results/v5/run_results.json
  tests/functional/artifacts/data/results/v6/run_results.json
  tests/functional/artifacts/data/state/v1/manifest.json
  tests/functional/artifacts/data/state/v10/manifest.json
  tests/functional/artifacts/data/state/v11/manifest.json
  tests/functional/artifacts/data/state/v12/manifest.json
  tests/functional/artifacts/data/state/v2/manifest.json
  tests/functional/artifacts/data/state/v3/manifest.json
  tests/functional/artifacts/data/state/v4/manifest.json
  tests/functional/artifacts/data/state/v5/manifest.json
  tests/functional/artifacts/data/state/v6/manifest.json
  tests/functional/artifacts/data/state/v7/manifest.json
  tests/functional/artifacts/data/state/v8/manifest.json
  tests/functional/artifacts/data/state/v9/manifest.json
  tests/functional/artifacts/expected_manifest.py
  tests/functional/artifacts/expected_run_results.py
  tests/functional/artifacts/test_artifact_fields.py
  tests/functional/artifacts/test_artifacts.py
  tests/functional/artifacts/test_docs_generate_defer.py
  tests/functional/artifacts/test_override.py
  tests/functional/artifacts/test_previous_version_state.py
  tests/functional/artifacts/test_run_results.py
  tests/functional/build_command/fixtures.py
  tests/functional/build_command/test_build.py
  tests/functional/cli/test_cli_exit_codes.py
  tests/functional/cli/test_env_var_deprecations.py
  tests/functional/cli/test_error_handling.py
  tests/functional/cli/test_multioption.py
  tests/functional/cli/test_resolvers.py
  tests/functional/configs/fixtures.py
  tests/functional/configs/test_configs.py
  tests/functional/configs/test_configs_in_schema_files.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/configs/test_custom_node_colors_configs.py
  tests/functional/configs/test_disabled_configs.py
  tests/functional/configs/test_disabled_model.py
  tests/functional/configs/test_dupe_paths.py
  tests/functional/configs/test_get_default.py
  tests/functional/configs/test_grant_configs.py
  tests/functional/configs/test_indiv_tests.py
  tests/functional/configs/test_unused_configs.py
  tests/functional/duplicates/test_duplicate_analysis.py
  tests/functional/duplicates/test_duplicate_exposure.py
  tests/functional/duplicates/test_duplicate_macro.py
  tests/functional/duplicates/test_duplicate_metric.py
  tests/functional/duplicates/test_duplicate_model.py
  tests/functional/duplicates/test_duplicate_resource.py
  tests/functional/duplicates/test_duplicate_source.py
  tests/functional/simple_snapshot/test_missing_strategy_snapshot.py
Labels: cla:yes, Skip Changelog

#113 [Regression] Fix psycopg2 version install
  .changes/unreleased/Fixes-20240605-202614.yaml
  .github/scripts/psycopg2-check.sh
  .github/workflows/integration-tests.yml
  .gitignore
  README.md
  pyproject.toml
  tests/functional/test_selection/conftest.py
  tests/functional/test_selection/test_selection_expansion.py
Labels: cla:yes, backport 1.8.latest

#115 update user docs-issue workflow
  .github/workflows/docs-issue.yml
Labels: cla:yes, Skip Changelog

#116 Add skip option and remove version_number
  .github/workflows/release-internal.yml
Labels: cla:yes, Skip Changelog

#117 [Regression] [backport 1.8.latest] Fix psycopg2 version install (#113)
  .changes/unreleased/Fixes-20240605-202614.yaml
  .github/scripts/psycopg2-check.sh
  .github/workflows/integration-tests.yml
  .gitignore
  README.md
  pyproject.toml
  tests/functional/configs/fixtures.py
  tests/functional/configs/test_configs.py
  tests/functional/configs/test_configs_in_schema_files.py
  tests/functional/configs/test_contract_configs.py
  tests/functional/configs/test_custom_node_colors_configs.py
  tests/functional/configs/test_disabled_configs.py
  tests/functional/configs/test_disabled_model.py
  tests/functional/configs/test_dupe_paths.py
  tests/functional/configs/test_get_default.py
  tests/functional/configs/test_grant_configs.py
  tests/functional/configs/test_indiv_tests.py
  tests/functional/configs/test_unused_configs.py
  tests/functional/simple_snapshot/data/invalidate_postgres.sql
  tests/functional/simple_snapshot/data/seed_pg.sql
  tests/functional/simple_snapshot/data/shared_macros.sql
  tests/functional/simple_snapshot/data/update.sql
  tests/functional/simple_snapshot/fixtures.py
  tests/functional/simple_snapshot/test_basic_snapshot.py
  tests/functional/simple_snapshot/test_changing_check_cols_snapshot.py
  tests/functional/simple_snapshot/test_changing_strategy_snapshot.py
  tests/functional/simple_snapshot/test_check_cols_snapshot.py
  tests/functional/simple_snapshot/test_check_cols_updated_at_snapshot.py
  tests/functional/simple_snapshot/test_comment_ending_snapshot.py
  tests/functional/simple_snapshot/test_cross_schema_snapshot.py
  tests/functional/simple_snapshot/test_hard_delete_snapshot.py
  tests/functional/simple_snapshot/test_invalid_namespace_snapshot.py
  tests/functional/simple_snapshot/test_long_text_snapshot.py
  tests/functional/simple_snapshot/test_missing_strategy_snapshot.py
  tests/functional/simple_snapshot/test_renamed_source_snapshot.py
  tests/functional/simple_snapshot/test_select_exclude_snapshot.py
  tests/functional/simple_snapshot/test_slow_query_snapshot.py
  tests/functional/test_selection/conftest.py
  tests/functional/test_selection/test_selection_expansion.py
Labels: cla:yes
